parameters:
  export.configuration:

    node:
      article:

        - source: title
          destination: title
          processor: PropertyProcessor

        - source: created
          destination: created
          processor: PropertyProcessor

        - source: body
          destination: body
          processor: LongTextAndSummaryProcessor
