parameters:
  drupal.root: './site/web'
  drupal.uri: 'http://drupal.docker.localhost:8000'

  export.root: './content'
  export.base_url: 'http://example.com'

  export.configuration: []

services:
  _defaults:
    autowire: true

  OpenEuropa\DrupalSiteMigration\:
    resource: '../src'

  OpenEuropa\DrupalSiteMigration\Processor\:
    resource: '../src/Processor'
    arguments: ['@OpenEuropa\DrupalSiteMigration\Drupal\Driver']

  OpenEuropa\DrupalSiteMigration\ExportWriter:
    arguments: ['%export.root%', '@Symfony\Component\Filesystem\Filesystem']

  OpenEuropa\DrupalSiteMigration\Drupal\Driver:
    arguments: ['%drupal.root%', '%drupal.uri%']
    calls:
      - [setCoreFromVersion]

  League\Fractal\Manager:
    calls:
      - [setSerializer, ['@League\Fractal\Serializer\JsonApiSerializer']]

  League\Fractal\Serializer\JsonApiSerializer:
    arguments: ['%export.base_url%']

  Symfony\Component\Console\Application:
    public: true

  Symfony\Component\Filesystem\Filesystem:
    shared: false

