parameters:
  export_root: './content'
  fractal.base_url: 'http://example.com'
  drupal.root: './site/web'
  drupal.uri: 'http://drupal.docker.localhost:8000'

services:
  _defaults:
    autowire: true

  OpenEuropa\DrupalSiteMigration\:
    resource: '../src'

  OpenEuropa\DrupalSiteMigration\ExportWriter:
    arguments: ['%export_root%', '@Symfony\Component\Filesystem\Filesystem']

  Drupal\Driver\DrupalDriver:
    arguments: ['%drupal.root%', '%drupal.uri%']
    calls:
      - [setCoreFromVersion]

  League\Fractal\Manager:
    calls:
      - [setSerializer, ['@League\Fractal\Serializer\JsonApiSerializer']]

  League\Fractal\Serializer\JsonApiSerializer:
    arguments: ['%fractal.base_url%']

  Symfony\Component\Console\Application:
    public: true

  Symfony\Component\Filesystem\Filesystem:
    shared: false

